# Generated by Django 5.2 on 2025-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default=''),
        ),
    ]
