# Generated by Django 5.2.6 on 2025-09-30 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_prodapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('GJ', 'Gujarat'), ('MH', 'Maharashtra'), ('RJ', 'Rajasthan'), ('PB', 'Punjab'), ('HR', 'Haryana'), ('UP', 'Uttar Pradesh'), ('MP', 'Madhya Pradesh'), ('BR', 'Bihar'), ('WB', 'West Bengal'), ('OD', 'Odisha'), ('JH', 'Jharkhand'), ('CG', 'Chhattisgarh'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('KL', 'Kerala')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
